# Generated by Django 5.1 on 2024-08-18 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_menuitem_category_alter_menuitem_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
