# Generated by Django 5.1 on 2024-09-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
