# Generated by Django 5.1 on 2024-10-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_rename_created_at_order_ordered_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
        migrations.DeleteModel(
            name='StaffProfile',
        ),
    ]
