# Generated by Django 5.1 on 2024-10-02 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_employee_first_name_alter_employee_joinedon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='login',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
        ),
    ]
