# Generated by Django 5.1 on 2024-10-02 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_remove_employee_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
