# Generated by Django 5.1 on 2024-10-04 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_delete_customer_remove_employee_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='employee',
        ),
        migrations.DeleteModel(
            name='EmployeeDashboard',
        ),
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
    ]
