# Generated by Django 5.1 on 2024-10-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_employee_email_employee_password_login_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin',
            name='role',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='signin',
            name='place',
            field=models.CharField(default='', max_length=100),
        ),
    ]
