# Generated by Django 5.1 on 2024-10-04 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_signin_role_alter_signin_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='login',
        ),
    ]
