# Generated by Django 5.1 on 2024-10-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='customer',
            field=models.CharField(max_length=100),
        ),
    ]
