# Generated by Django 5.1 on 2024-10-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_alter_feedback_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comments',
            field=models.CharField(max_length=1000),
        ),
    ]
