# Generated by Django 5.1 on 2024-10-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_menuitem_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
    ]
