# Generated by Django 5.1 on 2024-10-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_rename_first_name_employee_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedashboard',
            name='reservations',
        ),
        migrations.AddField(
            model_name='employee',
            name='place',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
