# Generated by Django 5.1 on 2024-10-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_alter_leaverequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='employee',
        ),
        migrations.DeleteModel(
            name='EmployeeDashboard',
        ),
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
    ]
