# Generated by Django 5.1 on 2024-10-14 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0060_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
