# Generated by Django 5.1 on 2024-10-17 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0061_delete_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
