# Generated by Django 5.1 on 2024-10-19 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0065_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedashboard',
            name='orders',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
