# Generated by Django 5.1 on 2024-10-19 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0069_order_employeedashboard_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedashboard',
            name='orders',
        ),
    ]
