# Generated by Django 5.1 on 2024-10-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0075_menuitem_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='customer',
            new_name='customer_name',
        ),
    ]
