# Generated by Django 5.1 on 2024-10-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0076_rename_customer_feedback_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='customer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
